version: '3.8'  # You can set the appropriate version based on your needs
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"   # Expose Jenkins UI on port 8080
      - "50000:50000" # Expose Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Use the host's Docker socket
    user: root # Run as root to allow installation of packages

volumes:
  jenkins_home:
